**Importing Requried Libraries**

In [1]:
from tensorflow.keras.preprocessing.text import one_hot


**Dataset**

In [3]:
text_data=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'undersatnd the meaning of word',
    'your videos are good',
]

**Defining Vocab Size**

In [4]:
vocab_size=10000

**One Hot Representation**

In [5]:
one_hot_rep=[one_hot(words,vocab_size) for words in text_data] # Using List comprehension here 
one_hot_rep

[[492, 7555, 9713, 3401],
 [492, 7555, 9713, 6976],
 [492, 1912, 9713, 9308],
 [2020, 8675, 9195, 3796, 4434],
 [9956, 492, 1678, 9713, 2047],
 [172, 2533, 6116, 3796]]

**Word Embeddings**

In [6]:
#Importing Required Libraries 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embbeded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embbeded_doc)

[[   0    0    0    0  492 7555 9713 3401]
 [   0    0    0    0  492 7555 9713 6976]
 [   0    0    0    0  492 1912 9713 9308]
 [   0    0    0 2020 8675 9195 3796 4434]
 [   0    0    0 9956  492 1678 9713 2047]
 [   0    0    0    0  172 2533 6116 3796]]


**Feature Representation**

In [8]:
dim=10

In [9]:
#Intializing the model 
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\awais\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
#Building the model 
model.build(input_shape=(None, sent_length))


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embbeded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[-3.10284626e-02, -2.46221665e-02,  3.92534249e-02,
         -4.48003411e-05,  1.70067064e-02, -1.86393745e-02,
         -4.49567810e-02,  3.30704339e-02,  3.57068516e-02,
          4.60423939e-02],
        [-3.10284626e-02, -2.46221665e-02,  3.92534249e-02,
         -4.48003411e-05,  1.70067064e-02, -1.86393745e-02,
         -4.49567810e-02,  3.30704339e-02,  3.57068516e-02,
          4.60423939e-02],
        [-3.10284626e-02, -2.46221665e-02,  3.92534249e-02,
         -4.48003411e-05,  1.70067064e-02, -1.86393745e-02,
         -4.49567810e-02,  3.30704339e-02,  3.57068516e-02,
          4.60423939e-02],
        [-3.10284626e-02, -2.46221665e-02,  3.92534249e-02,
         -4.48003411e-05,  1.70067064e-02, -1.86393745e-02,
         -4.49567810e-02,  3.30704339e-02,  3.57068516e-02,
          4.60423939e-02],
        [ 4.03604656e-03,  9.94700193e-03,  3.37487720e-02,
         -1.98453311e-02,  1.74358971e-02,  4.75326665e-02,
          1.59434192e-02, -2.80389078e-02, -4.268359

In [16]:
embbeded_doc[0]

array([   0,    0,    0,    0,  492, 7555, 9713, 3401])