**Importing Requried Libraries**

In [15]:
from tensorflow.keras.preprocessing.text import one_hot


**Dataset**

In [16]:
text_data=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'undersatnd the meaning of word',
    'your videos are good',
]

**Defining Vocab Size**

In [17]:
vocab_size=10000

**One Hot Representation**

In [18]:
one_hot_rep=[one_hot(words,vocab_size) for words in text_data] # Using List comprehension here 
one_hot_rep

[[4153, 3102, 2939, 9103],
 [4153, 3102, 2939, 6139],
 [4153, 3524, 2939, 7263],
 [8618, 7510, 2794, 4535, 4100],
 [1673, 4153, 596, 2939, 1364],
 [8334, 3840, 5390, 4535]]

**Word Embeddings**

In [19]:
#Importing Required Libraries 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [20]:
sent_length=8
embbeded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embbeded_doc)

[[   0    0    0    0 4153 3102 2939 9103]
 [   0    0    0    0 4153 3102 2939 6139]
 [   0    0    0    0 4153 3524 2939 7263]
 [   0    0    0 8618 7510 2794 4535 4100]
 [   0    0    0 1673 4153  596 2939 1364]
 [   0    0    0    0 8334 3840 5390 4535]]


**Feature Representation**

In [21]:
dim=10

In [25]:
#Intializing the model 
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [27]:
#Building the model 
model.build(input_shape=(None, sent_length))


In [28]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)